/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppAddEnseignant {}
  interface AppAddEnseignantAttributes extends StencilHTMLAttributes {}

  interface AppDetailsEnseignant {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppDetailsEnseignantAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppListEnseignant {}
  interface AppListEnseignantAttributes extends StencilHTMLAttributes {}

  interface AppSearchEnseignant {}
  interface AppSearchEnseignantAttributes extends StencilHTMLAttributes {}

  interface AppAddFormation {}
  interface AppAddFormationAttributes extends StencilHTMLAttributes {}

  interface AppDetailsFormation {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppDetailsFormationAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppEditFormation {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppEditFormationAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppListFormation {}
  interface AppListFormationAttributes extends StencilHTMLAttributes {}

  interface AppSearchFormation {}
  interface AppSearchFormationAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAddEnseignant': Components.AppAddEnseignant;
    'AppDetailsEnseignant': Components.AppDetailsEnseignant;
    'AppListEnseignant': Components.AppListEnseignant;
    'AppSearchEnseignant': Components.AppSearchEnseignant;
    'AppAddFormation': Components.AppAddFormation;
    'AppDetailsFormation': Components.AppDetailsFormation;
    'AppEditFormation': Components.AppEditFormation;
    'AppListFormation': Components.AppListFormation;
    'AppSearchFormation': Components.AppSearchFormation;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'app-add-enseignant': Components.AppAddEnseignantAttributes;
    'app-details-enseignant': Components.AppDetailsEnseignantAttributes;
    'app-list-enseignant': Components.AppListEnseignantAttributes;
    'app-search-enseignant': Components.AppSearchEnseignantAttributes;
    'app-add-formation': Components.AppAddFormationAttributes;
    'app-details-formation': Components.AppDetailsFormationAttributes;
    'app-edit-formation': Components.AppEditFormationAttributes;
    'app-list-formation': Components.AppListFormationAttributes;
    'app-search-formation': Components.AppSearchFormationAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLAppAddEnseignantElement extends Components.AppAddEnseignant, HTMLStencilElement {}
  var HTMLAppAddEnseignantElement: {
    prototype: HTMLAppAddEnseignantElement;
    new (): HTMLAppAddEnseignantElement;
  };

  interface HTMLAppDetailsEnseignantElement extends Components.AppDetailsEnseignant, HTMLStencilElement {}
  var HTMLAppDetailsEnseignantElement: {
    prototype: HTMLAppDetailsEnseignantElement;
    new (): HTMLAppDetailsEnseignantElement;
  };

  interface HTMLAppListEnseignantElement extends Components.AppListEnseignant, HTMLStencilElement {}
  var HTMLAppListEnseignantElement: {
    prototype: HTMLAppListEnseignantElement;
    new (): HTMLAppListEnseignantElement;
  };

  interface HTMLAppSearchEnseignantElement extends Components.AppSearchEnseignant, HTMLStencilElement {}
  var HTMLAppSearchEnseignantElement: {
    prototype: HTMLAppSearchEnseignantElement;
    new (): HTMLAppSearchEnseignantElement;
  };

  interface HTMLAppAddFormationElement extends Components.AppAddFormation, HTMLStencilElement {}
  var HTMLAppAddFormationElement: {
    prototype: HTMLAppAddFormationElement;
    new (): HTMLAppAddFormationElement;
  };

  interface HTMLAppDetailsFormationElement extends Components.AppDetailsFormation, HTMLStencilElement {}
  var HTMLAppDetailsFormationElement: {
    prototype: HTMLAppDetailsFormationElement;
    new (): HTMLAppDetailsFormationElement;
  };

  interface HTMLAppEditFormationElement extends Components.AppEditFormation, HTMLStencilElement {}
  var HTMLAppEditFormationElement: {
    prototype: HTMLAppEditFormationElement;
    new (): HTMLAppEditFormationElement;
  };

  interface HTMLAppListFormationElement extends Components.AppListFormation, HTMLStencilElement {}
  var HTMLAppListFormationElement: {
    prototype: HTMLAppListFormationElement;
    new (): HTMLAppListFormationElement;
  };

  interface HTMLAppSearchFormationElement extends Components.AppSearchFormation, HTMLStencilElement {}
  var HTMLAppSearchFormationElement: {
    prototype: HTMLAppSearchFormationElement;
    new (): HTMLAppSearchFormationElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-add-enseignant': HTMLAppAddEnseignantElement
    'app-details-enseignant': HTMLAppDetailsEnseignantElement
    'app-list-enseignant': HTMLAppListEnseignantElement
    'app-search-enseignant': HTMLAppSearchEnseignantElement
    'app-add-formation': HTMLAppAddFormationElement
    'app-details-formation': HTMLAppDetailsFormationElement
    'app-edit-formation': HTMLAppEditFormationElement
    'app-list-formation': HTMLAppListFormationElement
    'app-search-formation': HTMLAppSearchFormationElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'app-add-enseignant': HTMLAppAddEnseignantElement;
    'app-details-enseignant': HTMLAppDetailsEnseignantElement;
    'app-list-enseignant': HTMLAppListEnseignantElement;
    'app-search-enseignant': HTMLAppSearchEnseignantElement;
    'app-add-formation': HTMLAppAddFormationElement;
    'app-details-formation': HTMLAppDetailsFormationElement;
    'app-edit-formation': HTMLAppEditFormationElement;
    'app-list-formation': HTMLAppListFormationElement;
    'app-search-formation': HTMLAppSearchFormationElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
